name = "latino-leaders-2026"
pages_build_output_dir = "."
compatibility_date = "2024-01-01"

# D1 Database binding for Pages Functions
[[d1_databases]]
binding = "DB"
database_name = "young-latino-candidates"
database_id = "f68d30e5-a0a0-4356-9347-cd64e2ae98f7"

